// Erzeugt die ARCHITECTURE.md aus dem Graphen. Adaptiv (zeigt nur Abschnitte mit Daten) und
// zweisprachig: Englisch als Default, config.lang: "de" optional. Deterministisch sortiert.

const L = {
  en: {
    map: "Architecture Map",
    autogen: "Auto-generated by **Cartograph** (`cartograph build`) · do not edit by hand",
    lightTs: "light analysis: `typescript` not found in project",
    knowledge: "Project knowledge, decisions & open points",
    behind: (n, b) =>
      `> ⚠️ **Warning:** ${n} commit(s) behind \`origin/${b}\` — the map may reflect stale code. \`git pull\` recommended.`,
    overview: "Overview",
    metric: "Metric",
    value: "Value",
    files: "Files",
    pages: "Pages",
    apiRoutes: "API routes",
    components: "Components",
    libModules: "lib/util modules",
    models: "Data models",
    clientComponents: "Client components",
    empty: "_No source files yet — the map grows as you add and commit code._",
    fileTypes: "File types",
    pagesH: (n) => `Pages (${n})`,
    apiH: (n) => `API routes (${n})`,
    other: "(other)",
    dataModelH: (n) => `Data model — ${n} models`,
    modelUses: "Model ← files that use it (top 5):",
    unused: "_(unused)_",
    hubs: "Hubs (most imported)",
    topDeps: "Top external dependencies",
    orphans: "Orphaned modules",
    orphansDesc: "No incoming imports (possibly dead or only used dynamically):",
    more: (n) => `… +${n} more`,
    docs: "Docs",
  },
  de: {
    map: "Architektur-Karte",
    autogen: "Auto-generiert von **Cartograph** (`cartograph build`) · NICHT von Hand editieren",
    lightTs: "Light-Analyse: `typescript` nicht im Projekt gefunden",
    knowledge: "Projektwissen, Entscheidungen & offene Punkte",
    behind: (n, b) =>
      `> ⚠️ **Achtung:** ${n} Commit(s) hinter \`origin/${b}\` — die Karte spiegelt evtl. veralteten Code. \`git pull\` empfohlen.`,
    overview: "Überblick",
    metric: "Kennzahl",
    value: "Wert",
    files: "Dateien",
    pages: "Seiten",
    apiRoutes: "API-Routen",
    components: "Komponenten",
    libModules: "lib-/util-Module",
    models: "Datenmodelle",
    clientComponents: "Client-Components",
    empty: "_Noch keine Quelldateien — die Karte wächst, sobald du Code hinzufügst und committest._",
    fileTypes: "Dateitypen",
    pagesH: (n) => `Seiten (${n})`,
    apiH: (n) => `API-Routen (${n})`,
    other: "(sonstige)",
    dataModelH: (n) => `Datenmodell — ${n} Modelle`,
    modelUses: "Modell ← Dateien, die es verwenden (Top 5):",
    unused: "_(ungenutzt)_",
    hubs: "Hubs (meist-importiert)",
    topDeps: "Wichtigste externe Abhängigkeiten",
    orphans: "Verwaiste Module",
    orphansDesc: "Kein eingehender Import (evtl. tot oder nur dynamisch genutzt):",
    more: (n) => `… +${n} weitere`,
    docs: "Doku",
  },
};

export function renderArchitecture(graph, config) {
  const { name, stats, models, modelUsage, pages, apiRoutes, hubs, orphans, topExternals, byExt, sync, usedTs } = graph;
  const t = L[config.lang] || L.en;
  const lines = [];
  const push = (s = "") => lines.push(s);

  push(`# 🗺️ ${name} — ${t.map}`);
  push(`> ${t.autogen}`);
  push("");
  const facts = [
    config.language && config.language !== "unknown" ? config.language : null,
    config.framework && config.framework !== "none" ? config.framework : null,
    config.orm && config.orm !== "none" ? config.orm : null,
  ].filter(Boolean);
  if (facts.length) push(`**Stack:** ${facts.join(" · ")}${usedTs === false ? ` · _(${t.lightTs})_` : ""}`);
  push(`${t.knowledge} → [\`memory/INDEX.md\`](memory/INDEX.md)`);

  if (sync && sync.behind > 0) {
    push("");
    push(t.behind(sync.behind, sync.branch));
  }

  // Docs (aus config.docs, relativ zum Repo-Root → ../)
  if (config.docs && config.docs.length) {
    push("");
    push(`**${t.docs}:** ${config.docs.map((d) => `[\`${d}\`](../${d})`).join(" · ")}`);
  }

  push("");
  push(`## ${t.overview}`);
  push(`| ${t.metric} | ${t.value} |`);
  push("|---|---|");
  push(`| ${t.files} | ${stats.files} |`);
  if (stats.pages) push(`| ${t.pages} | ${stats.pages} |`);
  if (stats.apiRoutes) push(`| ${t.apiRoutes} | ${stats.apiRoutes} |`);
  if (stats.components) push(`| ${t.components} | ${stats.components} |`);
  if (stats.libModules) push(`| ${t.libModules} | ${stats.libModules} |`);
  if (stats.models) push(`| ${t.models} | ${stats.models} |`);
  if (stats.clientComponents) push(`| ${t.clientComponents} | ${stats.clientComponents} |`);

  if (stats.files === 0) {
    push("");
    push(t.empty);
    push("");
    return lines.join("\n") + "\n";
  }

  const exts = Object.entries(byExt).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  if (exts.length > 1) {
    push("");
    push(`## ${t.fileTypes}`);
    push(exts.map(([e, n]) => `\`${e}\` ${n}`).join(" · "));
  }

  if (pages.length) {
    push("");
    push(`## ${t.pagesH(pages.length)}`);
    for (const p of pages) push(`- \`${p.url}\` → ${p.file}`);
  }

  if (apiRoutes.length) {
    push("");
    push(`## ${t.apiH(apiRoutes.length)}`);
    const groups = {};
    for (const r of apiRoutes) {
      const segs = r.url.split("/").filter(Boolean);
      const key = segs[0] === "api" ? `/api/${segs[1] ?? "(root)"}` : t.other;
      (groups[key] ??= []).push(r);
    }
    for (const key of Object.keys(groups).sort()) {
      push("");
      push(`**${key}**`);
      for (const r of groups[key]) push(`- \`${r.url}\` · ${(r.methods || []).join(", ") || "—"} → ${r.file}`);
    }
  }

  if (models.length) {
    push("");
    push(`## ${t.dataModelH(models.length)}`);
    push(t.modelUses);
    push("");
    const sorted = [...models].sort((a, b) => (modelUsage[b]?.length ?? 0) - (modelUsage[a]?.length ?? 0) || a.localeCompare(b));
    for (const m of sorted) {
      const u = modelUsage[m] ?? [];
      push(`- **${m}** ← ${u.length}× ${u.length ? `· ${u.slice(0, 5).join(", ")}${u.length > 5 ? " …" : ""}` : t.unused}`);
    }
  }

  if (hubs.length) {
    push("");
    push(`## ${t.hubs}`);
    for (const h of hubs) push(`- ${h.file} ← ${h.inDegree}×`);
  }

  if (topExternals && topExternals.length) {
    push("");
    push(`## ${t.topDeps}`);
    push(topExternals.map((e) => `${e.name} (${e.count})`).join(" · "));
  }

  if (orphans.length) {
    push("");
    push(`## ${t.orphans}`);
    push(t.orphansDesc);
    for (const o of orphans.slice(0, 30)) push(`- ${o}`);
    if (orphans.length > 30) push(`- ${t.more(orphans.length - 30)}`);
  }

  push("");
  return lines.join("\n") + "\n";
}
